name: intelliguard
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  multi_image_picker: ^4.6.6+rc.1
  image_picker: ^0.6.3+4
  http: ^0.12.0+4
  provider: ^4.0.2
  animated_text_kit: ^1.3.0
  camera: ^0.5.7+4
  path: ^1.6.4
  dio: ^3.0.9
  carousel_slider: ^2.0.0
  path_provider: ^1.6.8
  http_parser: ^3.1.4
  charts_flutter: ^0.9.0
  webview_flutter: ^0.3.22+1
  shared_preferences: ^0.5.8
  flutter_beacon: ^0.3.0
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600